name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  container-job:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: node:16.14.2-alpine3.14

    services:
      db:
        image: postgres:14.2-alpine3.15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run database migrations
        run: yarn prisma migrate deploy
        env:
          DATABASE_URL: postgresql://postgres:postgres@db:5432/builders?schema=public

      - name: Run unit tests
        run: yarn test

      - name: Run end-to-end tests
        run: yarn test:e2e
